import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from "../components/Footer";
import Card from '../components/Card'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <Card />
      </main>

      <footer className={styles.footer}>
       <Footer />
      </footer>
    </div>
  )
}
